### ISSUE TITLE
What is our project title 

### ISSUE THREAD

**Issue by Daphnetatertot** [Daphnetatertot/Project_DAAM#3]
-Brew Find
-Brew Mate
-Brew Boy
-World of Beer (WOB)
-Beer Zip
-Alcohol in Your Area
-alcohol around
-Pint Finder
-Pint Boy
-Hop Service 
**-Brew Buddy**
-Brew Pal

**Comment by MartinCespedes** [comment]
I decided on Brew Buddy

**Comment by Daphnetatertot** [comment]
Martin runs the world so what he says goes

**Comment by asreedy82** [comment]
I concur
